server:
  port: 8092
spring:
  profiles:
    active: dev
  application:
    name: spring-boot-rabbit-mq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    queue:
      q1-name: mq-queue-1